<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5dd3f725b0c66',
	'title' => 'Flex Blocks',
	'fields' => array(
		array(
			'key' => 'field_5dd3f72a77ad2',
			'label' => 'flexblocks',
			'name' => 'flexblocks',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5dd3f73fed6c7' => array(
					'key' => 'layout_5dd3f73fed6c7',
					'name' => 'e-mail',
					'label' => 'E-Mail',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5dd3f74b77ad3',
							'label' => 'Address',
							'name' => 'address',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5dd560725c35a' => array(
					'key' => 'layout_5dd560725c35a',
					'name' => 'text_block',
					'label' => 'Text Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5dd55fa10fabb',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'br',
							'acfe_textarea_code' => 0,
						),
						array(
							'key' => 'field_5de188aeae12a',
							'label' => 'Position',
							'name' => 'position',
							'type' => 'button_group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'left' => 'left',
								'right' => 'right',
							),
							'allow_null' => 0,
							'default_value' => 'left',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5dd560895c35b' => array(
					'key' => 'layout_5dd560895c35b',
					'name' => 'spacing',
					'label' => 'Spacing',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_5dd962ec4c203' => array(
					'key' => 'layout_5dd962ec4c203',
					'name' => 'chaos',
					'label' => 'Chaos Slides',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5dd96255a9f64',
							'label' => 'Stacks',
							'name' => 'stacks',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Stack',
							'sub_fields' => array(
								array(
									'key' => 'field_5dd9627ca9f65',
									'label' => 'Images',
									'name' => 'images',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => 'Add image',
									'sub_fields' => array(
										array(
											'key' => 'field_5ddeb120cfc05',
											'label' => 'Image',
											'name' => 'id',
											'type' => 'image',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'id',
											'preview_size' => 'medium',
											'library' => 'all',
											'min_width' => '',
											'min_height' => '',
											'min_size' => '',
											'max_width' => '',
											'max_height' => '',
											'max_size' => '',
											'mime_types' => '',
										),
										array(
											'key' => 'field_5ddeb132cfc06',
											'label' => 'Caption',
											'name' => 'text',
											'type' => 'textarea',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'maxlength' => '',
											'rows' => 5,
											'new_lines' => 'br',
										),
										array(
											'key' => 'field_5ddeb14dcfc07',
											'label' => 'Link',
											'name' => 'link',
											'type' => 'page_link',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'post_type' => array(
												0 => 'projects',
											),
											'taxonomy' => '',
											'allow_null' => 0,
											'allow_archives' => 0,
											'multiple' => 0,
										),
										array(
											'key' => 'field_5ddebb955e159',
											'label' => 'Size',
											'name' => 'size',
											'type' => 'range',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => 100,
											'min' => 75,
											'max' => 125,
											'step' => '',
											'prepend' => '',
											'append' => '%',
										),
									),
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1575284904,
));

endif;